version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    labels:
      - "area-dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "area-dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"